# Generated by Django 3.2.5 on 2022-10-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_stores_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='item_picture',
            field=models.ImageField(upload_to='listingimages'),
        ),
    ]
